{"name": "test_2[2-3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 + 3) > 9", "trace": "data1 = 2, data2 = 3\n\n    @pytest.mark.parametrize('data1,data2',[(2,3),(4,5),(6,7)])\n    def test_2(data1,data2):\n        case_data.case_test_record_list.append('3')\n>       assert data1+data2 > 9\nE       assert (2 + 3) > 9\n\nD:\\autotest\\cases\\system\\AF\\8040\\test_param.py:23: AssertionError"}, "parameters": [{"name": "data1", "value": "2"}, {"name": "data2", "value": "3"}], "start": 1614493648055, "stop": 1614493648055, "uuid": "f02a2fbc-5713-4e80-b52e-0f93a7fd2fb1", "historyId": "10d056ce283d650a6306adc9e01abfe1", "testCaseId": "66c14860c93f84aeecc2424c28b86d59", "fullName": "cases.system.AF.8040.test_param#test_2", "labels": [{"name": "parentSuite", "value": "cases.system.AF.8040"}, {"name": "suite", "value": "test_param"}, {"name": "host", "value": "DESKTOP-H5OTV7O"}, {"name": "thread", "value": "13228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.system.AF.8040.test_param"}]}